### ISSUE TITLE
How would this deal with all IoT gadgets?

### ISSUE THREAD

**Issue by X-Ryl669** [RamboRogers/rfhunter#2]
Since now house are filled with IoT stuff, emitting Zigbee, Wifi, Bluetooth, LoRa and so on, how does this gizmo can make a difference between a genuine gadget and camera?

What about the non RF camera that are storing the video on a local µSD card without being RF connected?

How about a cameras in a main appliance object (like a SmartTV or a sattelite receiver, which will emit RF anyway)?

**Comment by Kalrkloss** [comment]
The IoT stuff usually sends only short bursts of data here and there, while an active camera sends a continuous stream of data, resulting in a constantly high field strength. You'll notice the difference.

**Comment by X-Ryl669** [comment]
> You'll notice the difference.

Only if there's a client on the camera, which is extremely unlikely to happen at the time you're using the detector.

> Big surprise you cannot detect non-RF camera with RF detector, lol.

Well, my point is that the main page is trying to "sell" the idea that the device will detect cameras. But it won't. 
Non RF camera will be undetected and RF camera won't likely be detected either (except in the very unlikely event that a client is connected and streaming from the camera at the exact time you're scanning the room).

But if you peak a WIFI burst (or any other radio burst), then it's even more likely it comes from the IoT gizmos than the camera itself. All devices (IoT and RF Camera) will have some (sparse) chatty transmission for maintaining their RF link, so there's ~ zero reason the RF activity is actually linked with a camera (well, close to zero in fact).

So maybe the main page should be modified to state that this is actually a RF detector for any RF emission in its receiving range and remove the part that reads `It's useful to find hidden cameras, wiretapping devices, and other RF-enabled devices.` because I don't see how you'll find hidden cameras with the detector, or a wiretapping device that, by definition will not use RF if they are wired. 

Also, since there's no dual antenna, you can't trilaterate the signal either so, at best, you'll get a pseudo range to the source (since you don't know the source power, you can only make relative measurement => better / worse). Good luck finding a device that's emitting its WIFI beacon every 10s that way, with all the reflections.

BTW, I'm not criticizing the amazing work you've done. Just that the subtitle is misleading.

I think it should say something like "This device is able to detect RF emission, and measure the relative RF power received".

**Comment by X-Ryl669** [comment]
> And if you really mean it, you need "Non-linear Junction Detector", prepare at least $10k. ;-)

When I was younger, I made a simple device that's detecting the electromagnetic field intensity. I was based on a cheap 1N4148 diode and a op amp + $1  micro controller (using its DAC and ADC). The basic physical principle was to bias the diode very close to the tripping point and ramp it up periodically. The "avalanche" effect, where the current grows exponentially triggers from ambient EM field (plus temperature, plus ..., but RF field effect is observable and temperature is usually constant). 
By periodically counting the time it takes for the diode to become conductive, you get a signal proportional to RF activity. 

The overall cost for the device was very low. I've just lost interest with playing with it very fast.

You can search for diode RF tester for simple schematic from the very basic to the most efficient design.

**Comment by RamboRogers** [comment]
This device detects long streams and signals.  I don't care about short bursts.  It's also barelines on bootup so it will alert off baseline.  If you turn it on directly next to AP it's unlikely it will alarm much after.  You want to power it on and it will alert as you get close to a higher signal versus baseline.
