### ISSUE TITLE
Add link to the Antennas used

### ISSUE THREAD

**Issue by Radiergummi** [RamboRogers/rfhunter#5]
I would love to know where you got the antenna on the purple RF Hunter in the pictures. Would you mind adding the link to the part list?

**Comment by lukeswitz** [comment]
I can’t say for sure but it would make sense it’s a WROOM-32U. These have a UFL > SMA antenna pigtail adapter.

**Comment by RamboRogers** [comment]
I've used quite a few different random antenna. These are from Lora hacking with meshtastic

https://www.amazon.com/gp/product/B07LCKNN4H/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
https://www.amazon.com/gp/product/B0CTXL61LY/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
